export enum AuditAction {
    ORGANIZATION_CREATED = 'ORGANIZATION_CREATED',
    ORGANIZATION_UPDATED = 'ORGANIZATION_UPDATED',
    ROLE_CREATED = 'ROLE_CREATED',
    ROLE_UPDATED = 'ROLE_UPDATED',
    ADD_PATIENT_ROLE = 'ADD_PATIENT_ROLE',
    CREATE_PATIENT = 'CREATE_PATIENT',
    UPDATE_PATIENT = 'UPDATE_PATIENT',
    SUSPEND_PATIENT = 'SUSPEND_PATIENT',
    REGISTER_PAYMENT = 'REGISTER_PAYMENT',
    MEMBERSHIP_APPROVED = 'MEMBERSHIP_APPROVED',
    MEMBERSHIP_REJECTED = 'MEMBERSHIP_REJECTED',
    MEMBERSHIP_SUSPENDED = 'MEMBERSHIP_SUSPENDED',
}
